//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDTERMPROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public string MSSV { get; set; }
        public string HOTEN { get; set; }
        public string GIOITINH { get; set; }
        public string EMAIL { get; set; }
    }
}
